name: 'olist_project'
version: '1.0.0'
config-version: 2

profile: 'olist_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_project:
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts